### ISSUE TITLE
Weather Template Wont Change

### ISSUE THREAD

**Issue by Sitruk** [Shreyas-R/lovelace-wallpanel-screensaver#10]
I'm unable to alter the weather info_template using the instructions. All I would like to do is remove the "C" and  move the degree symbol closer to the temp.

**Comment by Shreyas-R** [comment]
@Sitruk If you are using HACS version (v1.0), then `info_template` is not yet supported. `info_template` was released under v1.1-alpha which requires manual installation. 

If you are using latest alpha version, then you can get this working with following code for `info_template`:
```yaml
wallpanel_screensaver:
  ...
  ...
  info_template: '
        <div id="wallpanel-screensaver-info-weather">{{ states["weather.home"].attributes.temperature }}° {{ states["weather.home"].state.replace(/(^|\s)[A-Za-zÀ-ÖØ-öø-ÿ]/g, c => c.toUpperCase()) }}</div>
        <div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit"}) }}</div>
        <div id="wallpanel-screensaver-info-date">{{ (new Date()).toLocaleDateString(undefined, {weekday: "short", year: "numeric", month: "short", day: "numeric"}) }}</div>
        '
```

![image](https://user-images.githubusercontent.com/7105098/168561922-5cc4f459-dcd0-46f0-84c3-70403a0ac0d3.png)

**Comment by Sitruk** [comment]
> @Sitruk If you are using HACS version (v1.0), then `info_template` is not yet supported. `info_template` was released under v1.1-alpha which requires manual installation.
> 
> If you are using latest alpha version, then you can get this working with following code for `info_template`:
> 
> ```yaml
> wallpanel_screensaver:
>   ...
>   ...
>   info_template: '
>         <div id="wallpanel-screensaver-info-weather">{{ states["weather.home"].attributes.temperature }}° {{ states["weather.home"].state.replace(/(^|\s)[A-Za-zÀ-ÖØ-öø-ÿ]/g, c => c.toUpperCase()) }}</div>
>         <div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit"}) }}</div>
>         <div id="wallpanel-screensaver-info-date">{{ (new Date()).toLocaleDateString(undefined, {weekday: "short", year: "numeric", month: "short", day: "numeric"}) }}</div>
>         '
> ```
> 
> ![image](https://user-images.githubusercontent.com/7105098/168561922-5cc4f459-dcd0-46f0-84c3-70403a0ac0d3.png)

Thank you for your prompt reply. I confirmed I'm configured correctly with v1.1alpha. To be certain, I replaced the js file with a fresh v1.1, copy and pasted your code into my dashboard yaml and I also verified the resource is included as part of the manual update instructions. I updated Home Assistant and rebooted the server. There is no change. It looks like it just reverts to the default config.

**Comment by Shreyas-R** [comment]
@Sitruk you have uninstalled the HACS version before attempting manual installation right?

Also, try to clear the cache in the browser in which you are running the HA dashboard and check. Browsers tend to cache the scripts.

**Comment by Sitruk** [comment]
Thank you. I removed all HACS traces and did a manual install. This fixed it.
