### ISSUE TITLE
I get an error when adding the config

### ISSUE THREAD

**Issue by Markobu98** [Shreyas-R/lovelace-wallpanel-screensaver#14]
I copied the default config and added it to my dashboard config. However I get this error message:

![image](https://user-images.githubusercontent.com/72013479/169847006-a1f740b1-0a37-4ffe-87b5-275c6cd4aba8.png)

And my config looks like this:

![image](https://user-images.githubusercontent.com/72013479/169847190-66797c60-beeb-4b94-b740-b088213f3361.png)

My guess is there is an error in line 20 but my knowledge of coding isnt enough to figure it out.

**Comment by Shreyas-R** [comment]
@Markobu98 there's some correction needed in the documentation which is causing this issue which will be covered in the next release. 

However, you don't need to copy and use the entire default config. You can get started with the config in usage examples and copy and modify only the config parameters you need.
