### ISSUE TITLE
Weather icons not found

### ISSUE THREAD

**Issue by magune** [Shreyas-R/lovelace-wallpanel-screensaver#15]
Thanks for the update!

I upgraded, and decided to enable the weather info on the screensaver at the same time.

The weather data shows, but the weather icon files cannot be found:
![image](https://user-images.githubusercontent.com/50596445/169982917-c6d5ea19-fcb7-4f34-8892-12310cf3dc6e.png)

The weather icons do however appear to have been installed:
![image](https://user-images.githubusercontent.com/50596445/169982985-9d6c26c9-1375-4b72-a347-91ff9d6a4e54.png)

![image](https://user-images.githubusercontent.com/50596445/169983031-92d3afc2-34fe-4513-a500-32dc231d975d.png)

Any suggestions?

**Comment by Shreyas-R** [comment]
If you can access your dashboard on a PC/MAC/Laptop, check if the weather icons are loading properly there. If you find the same issue there, then you can enable the debug console on your browser and share with me the error logs.

**Comment by magune** [comment]
Thanks. the logs are fairly weird, as far as I can understand with my limited technical skills in this area.

This is the log - weather icon images gives 404:
![image](https://user-images.githubusercontent.com/50596445/170053457-788d1182-f81b-4d8d-9672-87ccf489b140.png)

The interesting thing is the weather icons are read from /hacsfiles/skolmat-card/weather-icons/, not from inside the wall panel plugin folder!

Clearly, the skolmat-card plugin do not have any weather-icon folder:

![image](https://user-images.githubusercontent.com/50596445/170053961-b69e8466-dfca-4723-aab1-a13936a8cb40.png)

![image](https://user-images.githubusercontent.com/50596445/170053983-20ea9908-e7bd-4345-b17f-7873b5b58789.png)


But the wall panel card do, as expected:

![image](https://user-images.githubusercontent.com/50596445/170054024-d9fed3df-f5a4-428e-a85c-69b36f33963f.png)

The icon files are in the weather-icons folder as well.

I have added ?v2 to the resource as well, as outlined in your documentation.

![image](https://user-images.githubusercontent.com/50596445/170054171-f1b33960-ff2f-46bd-8ddf-4c2e7ced8744.png)


Very weirdly, it appears your wall panel plugin tries to load the icons from the folder tree of another card, not from the wall panel plug in folder tree.

**Comment by fuxing-at** [comment]
> 
> Very weirdly, it appears your wall panel plugin tries to load the icons from the folder tree of another card, not from the wall panel plug in folder tree.

Seems right, that the images are searched within a different folder:
<img id="weather-state-icon" src="/hacsfiles/light-popup-card/weather-icons/rainy-sun-above-horizon.svg" style="width: 64px; height: 64px; vertical-align: middle;">

**Comment by magune** [comment]
it works now, thanks!
