### ISSUE TITLE
12 hour time on screensaver

### ISSUE THREAD

**Issue by webshaun** [Shreyas-R/lovelace-wallpanel-screensaver#21]
I'm not sure which direction to go here.  It seems that instead of displaying a 12 hour time, I'm seeing a 24 hour time on the screensaver, so 13:37.  

In the line <div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit", hour12: config.hour_12}) }}</div>

I see 
hour12: config.hour_12

So I thought the intention was for it to display a 12 hour clock which is why I'm asking here.  My local settings are set to America/New York.  This doesn't seem to be an issue anywhere else on this instance.

**Comment by webshaun** [comment]
Sorry, just noticed the flag in the full instructions.

**Comment by Shreyas-R** [comment]
You have three options for time format if you are using or passing `info_template` parameter under `wallpanel_screensaver` config.

1) **_LOCALE DEFAULT_ :**  Remove `hour12: config.hour_12` text from the line `<div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit", hour12: config.hour_12}) }}</div>` in `info_template` parameter to set locale default settings.

```html
<div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit"}) }}</div>
```

2) **_HARDCODED_ :**  Hardcode `hour12: true` for 12 hours format and `hour12: false` for 24 hours format in the line `<div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit", hour12: config.hour_12}) }}</div>` in `info_template` parameter.

**Hardcoded 12 hours time format:**
```html
<div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit", hour12: true}) }}</div>
```
**Hardcoded 24 hours time format:**
```html
<div id="wallpanel-screensaver-info-time">{{ (new Date()).toLocaleTimeString(undefined, {hour: "2-digit", minute:"2-digit", hour12: false}) }}</div>
```

3) **_CONFIG BASED_ :**  Pass `hour_12: true`  for 12 hours format and `hour_12: false` for 24 hours format under `wallpanel_screensaver` config.
