### ISSUE TITLE
menu icon does reappear / not disappear on small devices

### ISSUE THREAD

**Issue by mondbaron** [Shreyas-R/lovelace-wallpanel-screensaver#24]
On small screens (e.g. a tablet or RPi dashboard) the menu icon in the top left corner does not hide with the sidebar. Further, on click it causes the screen to tint without any other effect.

I'd guess the custom style of this integration does not adapt properly to the smaller classes of the native responsive design in Lovelace/HA. Maybe the style overrides can be extended to thoses classes?

### Versions
- Home Assistent Core 2022.6.3
- Lovelace Wallpanel Screensaver 1.1.1

### Steps to reproduce

- use the minimal config
```
wallpanel_screensaver:
  enabled: true
  hide_sidebar: true
```
- resize the screen to less than 870px width
- watch the menu button reappear and try to click on it

**Comment by Shreyas-R** [comment]
I was able to replicate it.
