### ISSUE TITLE
Feature request: 24 hour hour clock setting

### ISSUE THREAD

**Issue by syphernl** [Shreyas-R/lovelace-wallpanel-screensaver#3]
Would it be possible to create a flag to toggle between 12/24 hours? 

Alternatively an `info_template` (like the original repo has) could also take care of this.

**Comment by Shreyas-R** [comment]
By default, the date and time format are fetched from the browser or device where the HA dashboard is running. You can change the locale settings of the browser or device to quickly switch this. 

Also, I have merged the recent changes from the original repo in the latest alpha release which supports info template. Some more things are to be pushed after which it'll be released to HACS. You can test alpha/beta builds by manually installing the files (Make sure to uninstall stable version from HACS before manual installation).
