### ISSUE TITLE
Feature request: disable screensaver on binary_sensor

### ISSUE THREAD

**Issue by syphernl** [Shreyas-R/lovelace-wallpanel-screensaver#4]
Would it be possible to exit the screensaver once a `binary_sensor` is switched to `on` (e.g. a motion sensor, door sensor etc). 

This should make it more seamless, without needing a tap on the screen to exit the screensaver mode.

**Comment by marcolega** [comment]
I am interested also. Is there any solution?

**Comment by lio0909** [comment]
Would love to see any functionality like this: in my case I would like to show the picture of the camera after someone rang the bell

**Comment by syphernl** [comment]
Closing since issue this repo is now deprecated. 
The project this was based on appears to have an option to toggle the screensaver based on a `binary_sensor`.
