### ISSUE TITLE
How to make dashboard button force screensaver into dark mode immediately?

### ISSUE THREAD

**Issue by magune** [Shreyas-R/lovelace-wallpanel-screensaver#8]
It would be really nice if it was possibly to add a button to my dashboard, that forces the screensaver into "black mode" upon button press.

That way, I could force a wall mounted ipad outside the bedroom to go black immediately at bed time, as I might want to have a longer (e.g. 30 minutes) black time on day time.

Is there any way to control the screensaver from a dashboard button, and "force it" into black mode immediately upon key press?

**Comment by Shreyas-R** [comment]
@magune Although not the same thing that you asked for, the `Night Mode` feature should be able to help you achieve similar configuration in an automated way without manual efforts.
